# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

WORKDIR /app

# Copy package manager files
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Install dependencies
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN pnpm run build

# Expose port if needed (the server seems to use stdio, so not exposing any port)

# Start the MCP server in stdio mode
CMD ["node", "dist/cli.js", "--stdio"]
